webtalk_init -webtalk_dir C:/Users/TanZh/Documents/cpu/HikariMIPS/HikariMIPS.sim/sim_1/behav/xsim/xsim.dir/hikari_mips_sopc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 25 11:10:50 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1a7b9759-ec18-4092-a8c5-b45c1ab5929e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b6cd11f0887b4e2fbd3a88ebeab3434f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "222" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "51.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "60" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "2798 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "609 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "11478" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "5198" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "21.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "515624_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1131745676 -regid "" -xml C:/Users/TanZh/Documents/cpu/HikariMIPS/HikariMIPS.sim/sim_1/behav/xsim/xsim.dir/hikari_mips_sopc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/TanZh/Documents/cpu/HikariMIPS/HikariMIPS.sim/sim_1/behav/xsim/xsim.dir/hikari_mips_sopc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/TanZh/Documents/cpu/HikariMIPS/HikariMIPS.sim/sim_1/behav/xsim/xsim.dir/hikari_mips_sopc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
