# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/HikariMIPS/HikariMIPS.cache/wt [current_project]
set_property parent.project_path D:/HikariMIPS/HikariMIPS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/HikariMIPS/HikariMIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/HikariMIPS/code/obj/inst_ram.coe
read_verilog -library xil_defaultlib {
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/defines.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/cp0_reg.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/ctrl.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/div.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/ex.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/ex_mem.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/hilo_reg.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/id.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/id_ex.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/if_id.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/mem.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/mem_wb.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/pc_reg.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/regfile.v
  D:/HikariMIPS/HikariMIPS.srcs/sources_1/new/hikari_mips.v
}
read_ip -quiet D:/HikariMIPS/HikariMIPS.srcs/sources_1/ip/unsigned_divider/unsigned_divider.xci

read_ip -quiet D:/HikariMIPS/HikariMIPS.srcs/sources_1/ip/signed_divider/signed_divider.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top hikari_mips -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef -incremental_synth hikari_mips.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hikari_mips_utilization_synth.rpt -pb hikari_mips_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
